# Generated by Django 5.0.4 on 2024-05-10 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intercambios_caritas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='login_attempts',
        ),
    ]
