# Generated by Django 5.0.4 on 2024-05-10 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambios_caritas', '0002_remove_usuario_login_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='login_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
