# Generated by Django 5.0.4 on 2024-05-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambios_caritas', '0004_remove_usuario_login_attempts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=280, null=True)),
                ('imagen', models.ImageField(upload_to='')),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('punto_encuentro', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
