# Generated by Django 5.0.4 on 2024-05-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambios_caritas', '0007_publicacion_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='usuario',
            field=models.CharField(default='', max_length=150),
        ),
    ]
