# Generated by Django 5.0.4 on 2024-05-14 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intercambios_caritas', '0008_alter_publicacion_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacion',
            old_name='usuario',
            new_name='usuario_dni',
        ),
    ]
