# Generated by Django 5.0.4 on 2024-05-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambios_caritas', '0009_rename_usuario_publicacion_usuario_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='usuario_nombre',
            field=models.CharField(default='', max_length=150),
        ),
    ]
