# Generated by Django 5.0.6 on 2024-05-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambios_caritas', '0010_publicacion_usuario_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='categoria',
            field=models.CharField(choices=[('Alimentos', 'Alimentos'), ('Ropa', 'Ropa'), ('Utiles escolares', 'Utiles escolares'), ('Artículos de limpieza', 'Artículos de limpieza')], default='Otros', max_length=50),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='estado',
            field=models.CharField(choices=[('Usado', 'Usado'), ('Nuevo', 'Nuevo')], default='Usado', max_length=50),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='punto_encuentro',
            field=models.CharField(choices=[('Negociable', 'Negociable'), ('La Plata', 'La Plata'), ('CABA', 'CABA'), ('Quilmes', 'Quilmes'), ('Temperley', 'Temperley')], default='Negociable', max_length=50),
        ),
    ]
