# Generated by Django 5.0.6 on 2024-05-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambios_caritas', '0011_alter_publicacion_categoria_alter_publicacion_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='descripcion',
            field=models.CharField(blank=True, default='Sin descripción', max_length=280),
        ),
    ]
