# Generated by Django 5.0.6 on 2024-05-27 20:10

import django.db.models.deletion
import intercambios_caritas.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambios_caritas', '0012_alter_publicacion_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='usuario',
            field=models.ForeignKey(default=intercambios_caritas.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
