# Generated by Django 5.0.6 on 2024-05-27 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intercambios_caritas', '0013_publicacion_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='usuario_dni',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='usuario_nombre',
        ),
    ]
