# Generated by Django 5.0.4 on 2024-05-31 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambios_caritas', '0014_remove_publicacion_usuario_dni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='estado',
            field=models.CharField(choices=[('Sin especificar', 'Sin especificar'), ('Usado', 'Usado'), ('Nuevo', 'Nuevo')], default='Sin especificar', max_length=50),
        ),
    ]
