# Generated by Django 5.0.4 on 2024-05-31 22:43

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambios_caritas', '0015_alter_publicacion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='dias_convenientes',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=100),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='franja_horaria',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
