# Generated by Django 5.0.4 on 2024-06-02 22:39

import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambios_caritas', '0016_publicacion_dias_convenientes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intercambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro_encuentro', models.CharField(choices=[('Negociable', 'Negociable'), ('La Plata', 'La Plata'), ('CABA', 'CABA'), ('Quilmes', 'Quilmes'), ('Temperley', 'Temperley')], max_length=50)),
                ('dias_convenientes', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=100)),
                ('franja_horaria_inicio', models.TimeField()),
                ('franja_horaria_fin', models.TimeField()),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('aceptada', models.BooleanField(default=False)),
                ('publicacion_demandada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_recibidas', to='intercambios_caritas.publicacion')),
                ('publicacion_ofertante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_realizadas', to='intercambios_caritas.publicacion')),
            ],
        ),
    ]
