# Generated by Django 5.0.4 on 2024-06-06 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambios_caritas', '0018_publicacion_franja_horaria_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intercambio',
            name='franja_horaria_fin',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AlterField(
            model_name='intercambio',
            name='franja_horaria_inicio',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
