# Generated by Django 5.0.4 on 2024-06-06 17:07

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intercambios_caritas', '0019_alter_intercambio_franja_horaria_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='punto_encuentro',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Negociable', 'Negociable'), ('La Plata', 'La Plata'), ('CABA', 'CABA'), ('Quilmes', 'Quilmes'), ('Temperley', 'Temperley')], max_length=100),
        ),
    ]
