# Generated by Django 5.0.4 on 2024-06-06 17:08

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambios_caritas', '0020_alter_publicacion_punto_encuentro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intercambio',
            name='centro_encuentro',
            field=models.CharField(choices=[('La Plata', 'La Plata'), ('CABA', 'CABA'), ('Quilmes', 'Quilmes'), ('Temperley', 'Temperley')], max_length=50),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='punto_encuentro',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('La Plata', 'La Plata'), ('CABA', 'CABA'), ('Quilmes', 'Quilmes'), ('Temperley', 'Temperley')], max_length=100),
        ),
    ]
