# Generated by Django 5.0.4 on 2024-06-06 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambios_caritas', '0021_alter_intercambio_centro_encuentro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intercambio',
            name='dias_convenientes',
        ),
        migrations.AddField(
            model_name='intercambio',
            name='fecha_intercambio',
            field=models.DateField(default=datetime.datetime(2024, 6, 12, 0, 0)),
        ),
    ]
