# Generated by Django 5.0.4 on 2024-06-06 19:42

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intercambios_caritas', '0022_remove_intercambio_dias_convenientes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intercambio',
            old_name='centro_encuentro',
            new_name='punto_encuentro',
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='dias_convenientes',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Monday', 'Lunes'), ('Tuesday', 'Martes'), ('Wednesday', 'Miércoles'), ('Thursday', 'Jueves'), ('Friday', 'Viernes'), ('Saturday', 'Sábado'), ('Sunday', 'Domingo')], max_length=100),
        ),
    ]
