# Generated by Django 5.0.4 on 2024-06-07 03:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambios_caritas', '0024_alter_publicacion_dias_convenientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intercambio',
            name='franja_horaria_fin',
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
    ]
