# Generated by Django 4.2.13 on 2024-06-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("intercambios_caritas", "0025_alter_intercambio_franja_horaria_fin"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="rol",
            field=models.CharField(
                choices=[
                    ("ADMINISTRADOR", "Administrador"),
                    ("USUARIO", "Usuario"),
                    ("MODERADOR", "Moderador"),
                ],
                default="USUARIO",
                max_length=20,
            ),
        ),
    ]
