# Generated by Django 5.0.4 on 2024-06-07 23:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambios_caritas', '0029_publicacion_disponible_para_intercambio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intercambio',
            name='franja_horaria_fin',
        ),
        migrations.RemoveField(
            model_name='intercambio',
            name='franja_horaria_inicio',
        ),
        migrations.AddField(
            model_name='intercambio',
            name='franja_horaria',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
