# Generated by Django 4.2.13 on 2024-06-09 04:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("intercambios_caritas", "0030_remove_intercambio_franja_horaria_fin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="filial",
            field=models.CharField(
                choices=[
                    ("N/A", "Notapplicable"),
                    ("CABA", "CABA"),
                    ("Quilmes", "Quilmes"),
                    ("Temperley", "Temperley"),
                ],
                default="N/A",
                max_length=20,
            ),
        ),
    ]
