# Generated by Django 5.0.4 on 2024-06-10 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambios_caritas', '0031_usuario_filial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intercambio',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada'), ('CANCELADA', 'Cancelada'), ('CONFIRMADA', 'Confirmada'), ('DESESTIMADA', 'Desestimada')], default='PENDIENTE', max_length=12),
        ),
    ]
