# Generated by Django 4.2.13 on 2024-06-12 01:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("intercambios_caritas", "0035_alter_intercambio_motivo_desestimacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="filial",
            field=models.CharField(
                choices=[
                    ("CABA", "CABA"),
                    ("Quilmes", "Quilmes"),
                    ("Temperley", "Temperley"),
                    ("La Plata", "La Plata"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
