# Generated by Django 5.0.6 on 2024-06-17 01:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambios_caritas', '0039_alter_usuario_email_alter_usuario_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intercambio',
            name='fecha_intercambio',
            field=models.DateField(default=datetime.datetime(2024, 7, 3, 0, 0)),
        ),
    ]
