# Generated by Django 5.0.6 on 2024-06-17 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intercambios_caritas', '0039_alter_publicacion_usuario'),
        ('intercambios_caritas', '0040_alter_intercambio_fecha_intercambio'),
    ]

    operations = [
    ]
