# Generated by Django 5.0.6 on 2024-06-17 19:53

import intercambios_caritas.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambios_caritas', '0042_alter_usuario_email_alter_usuario_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=models.SET(intercambios_caritas.models.get_deleted_user), to=settings.AUTH_USER_MODEL),
        ),
    ]
