# Generated by Django 5.0.6 on 2024-06-23 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intercambios_caritas', '0047_alter_publicacion_categoria_nueva'),
        ('intercambios_caritas', '0047_pregunta_respuesta'),
    ]

    operations = [
    ]
