# Generated by Django 5.0.4 on 2024-06-23 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambios_caritas', '0048_filial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='filial',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='intercambios_caritas.filial'),
        ),
    ]
