# Generated by Django 5.0.6 on 2024-06-26 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambios_caritas', '0050_alter_usuario_email_alter_usuario_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intercambio',
            name='donacion_descripcion',
            field=models.CharField(blank=True, default='Sin descripción', help_text='Descripción de la donación realizada', max_length=280, null=True, verbose_name='Descripción de la donación'),
        ),
        migrations.AddField(
            model_name='intercambio',
            name='hubo_donacion',
            field=models.BooleanField(default=False, help_text='Indica si hubo donación en el intercambio', verbose_name='Hubo donación'),
        ),
    ]
