# Generated by Django 5.0.6 on 2024-06-26 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambios_caritas', '0051_intercambio_donacion_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intercambio',
            name='calificacion_demandante',
            field=models.IntegerField(default=0, help_text='Calificación del demandante', verbose_name='Calificación del demandante'),
        ),
        migrations.AddField(
            model_name='intercambio',
            name='calificacion_ofertante',
            field=models.IntegerField(default=0, help_text='Calificación del ofertante', verbose_name='Calificación del ofertante'),
        ),
    ]
