# Generated by Django 5.0.4 on 2024-06-30 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambios_caritas', '0054_publicacion_filial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='filial',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='filial',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='intercambios_caritas.filial'),
            preserve_default=False,
        ),
    ]
