# Generated by Django 5.0.4 on 2024-07-01 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambios_caritas', '0058_remove_intercambio_punto_encuentro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intercambio',
            name='filial',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='intercambios_caritas.filial'),
        ),
    ]
