# Generated by Django 5.0.6 on 2024-07-03 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambios_caritas', '0060_alter_intercambio_filial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intercambio',
            name='calificacion_demandante_a_ofertante',
            field=models.IntegerField(blank=True, default=0, help_text='Calificación del demandante al ofertante', null=True, verbose_name='Calificación del demandante al ofertante'),
        ),
        migrations.AddField(
            model_name='intercambio',
            name='calificacion_ofertante_a_demandante',
            field=models.IntegerField(blank=True, default=0, help_text='Calificación del ofertante al demandante', null=True, verbose_name='Calificación del ofertante al demandante'),
        ),
    ]
