# Generated by Django 5.0.4 on 2024-07-03 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambios_caritas', '0065_notificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intercambio',
            name='filial',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='intercambios_caritas.filial'),
        ),
    ]
